---
abstract: 'E-mail toolkit for Japanese Mobile Phones'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-MIME-MobileJP
no_index:
  directory:
    - t
    - inc
provides:
  Email::MIME::MobileJP:
    file: lib/Email/MIME/MobileJP.pm
    version: 0.06
  Email::MIME::MobileJP::Creator:
    file: lib/Email/MIME/MobileJP/Creator.pm
    version: 0
  Email::MIME::MobileJP::Parser:
    file: lib/Email/MIME/MobileJP/Parser.pm
    version: 0
  Email::MIME::MobileJP::Template:
    file: lib/Email/MIME/MobileJP/Template.pm
    version: 0
requires:
  Email::Address: 1.892
  Email::Address::JP::Mobile: 0.05
  Email::Address::Loose: 0.01
  Email::MIME: 1.906
  Encode: 2.4
  Encode::JP::Mobile: 0.27
  Tiffany: 0.03
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
