---
abstract: 'E-mail toolkit for Japanese Mobile Phones'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.96
  Test::Requires: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Email-MIME-MobileJP
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Email::Address: 0
  Email::Address::JP::Mobile: 0
  Email::Address::Loose: 0
  Email::Date::Format: 0
  Email::MIME: 0
  Encode: 0
  Encode::JP::Mobile: 0
  Tiffany: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
